application: nops-gmsl
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /templates
  static_dir: templates

- url: /stores.json
  static_files: stores.json
  upload: stores.json

- url: /
  static_files: index.html
  upload: index.html
